#version: "3.9"

services:
  streamlit:
    build: .
    container_name: internetspeed
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    cap_add:
      - NET_RAW
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false
